import {
  LocalOffer as OfferIcon,
  AccountCircle,
  FavoriteBorder as FavoriteBorderIcon,
  Message as MessageIcon,
  AddBox as AddBoxIcon,
  ListAlt as ListAltIcon,
  AdminPanelSettings as AdminPanelSettingsIcon,
  Notifications as NotificationsIcon,
} from "@mui/icons-material";

export const menuItems = [
  {
    key: "offers",
    label: "offers",
    path: "/",
    icon: <OfferIcon />,
    show: (user) => true,
  },
  {
    key: "profile",
    label: "profile",
    path: "/profile",
    icon: <AccountCircle />,
    show: (user) => !!user,
  },
  {
    key: "favorites",
    label: "favorites",
    path: "/favorites",
    icon: <FavoriteBorderIcon />,
    show: (user) => !!user,
  },
  {
    key: "chat",
    label: "chat",
    path: "/chat-list",
    icon: <MessageIcon />,
    show: (user) => !!user,
  },
  {
    key: "create_offer",
    label: "create_offer",
    path: "/create-offer",
    icon: <AddBoxIcon />,
    show: (user) => user && (user.role === "provider" || user.role === "admin"),
  },
  {
    key: "my_offers",
    label: "my_offers",
    path: "/my-offers",
    icon: <ListAltIcon />,
    show: (user) => user && (user.role === "provider" || user.role === "admin"),
  },
  {
    key: "admin_panel",
    label: "admin_panel",
    path: "/admin",
    icon: <AdminPanelSettingsIcon />,
    show: (user) => user && user.role === "admin",
  },
  {
    key: "notifications",
    label: "notifications",
    path: "/notifications",
    icon: <NotificationsIcon />,
    show: () => true,
  },
  {
    key: "logout",
    label: "logout",
    icon: <AccountCircle />,
    isLogout: true,
    show: (user) => !!user,
  },
  {
    key: "login",
    label: "login",
    path: "/login",
    icon: <AccountCircle />,
    show: (user) => !user,
  },
];
